package pya.marlon.com.examplegreendao.sql.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pya.marlon.com.examplegreendao.sql.model.UserSQL;
import pya.marlon.com.examplegreendao.sql.model.PetSQL;
import pya.marlon.com.examplegreendao.sql.model.ToySQL;

import pya.marlon.com.examplegreendao.sql.model.UserSQLDao;
import pya.marlon.com.examplegreendao.sql.model.PetSQLDao;
import pya.marlon.com.examplegreendao.sql.model.ToySQLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userSQLDaoConfig;
    private final DaoConfig petSQLDaoConfig;
    private final DaoConfig toySQLDaoConfig;

    private final UserSQLDao userSQLDao;
    private final PetSQLDao petSQLDao;
    private final ToySQLDao toySQLDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userSQLDaoConfig = daoConfigMap.get(UserSQLDao.class).clone();
        userSQLDaoConfig.initIdentityScope(type);

        petSQLDaoConfig = daoConfigMap.get(PetSQLDao.class).clone();
        petSQLDaoConfig.initIdentityScope(type);

        toySQLDaoConfig = daoConfigMap.get(ToySQLDao.class).clone();
        toySQLDaoConfig.initIdentityScope(type);

        userSQLDao = new UserSQLDao(userSQLDaoConfig, this);
        petSQLDao = new PetSQLDao(petSQLDaoConfig, this);
        toySQLDao = new ToySQLDao(toySQLDaoConfig, this);

        registerDao(UserSQL.class, userSQLDao);
        registerDao(PetSQL.class, petSQLDao);
        registerDao(ToySQL.class, toySQLDao);
    }
    
    public void clear() {
        userSQLDaoConfig.clearIdentityScope();
        petSQLDaoConfig.clearIdentityScope();
        toySQLDaoConfig.clearIdentityScope();
    }

    public UserSQLDao getUserSQLDao() {
        return userSQLDao;
    }

    public PetSQLDao getPetSQLDao() {
        return petSQLDao;
    }

    public ToySQLDao getToySQLDao() {
        return toySQLDao;
    }

}
