package pya.marlon.com.examplegreendao.sql.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PET_SQL".
 */
@Entity
public class PetSQL {

    @Id(autoincrement = true)
    private Long id;
    private Integer fk_idUser;
    private String name;
    private String alias;
    private Double weight;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PetSQL() {
    }

    public PetSQL(Long id) {
        this.id = id;
    }

    @Generated
    public PetSQL(Long id, Integer fk_idUser, String name, String alias, Double weight) {
        this.id = id;
        this.fk_idUser = fk_idUser;
        this.name = name;
        this.alias = alias;
        this.weight = weight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFk_idUser() {
        return fk_idUser;
    }

    public void setFk_idUser(Integer fk_idUser) {
        this.fk_idUser = fk_idUser;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public String toString() {
        return "PetSQL{" +
                "id=" + id +
                ", fk_idUser=" + fk_idUser +
                ", name='" + name + '\'' +
                ", alias='" + alias + '\'' +
                ", weight=" + weight +
                '}';
    }
}
