package pya.marlon.com.examplegreendao.sql.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PET_SQL".
*/
public class PetSQLDao extends AbstractDao<PetSQL, Long> {

    public static final String TABLENAME = "PET_SQL";

    /**
     * Properties of entity PetSQL.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fk_idUser = new Property(1, Integer.class, "fk_idUser", false, "FK_ID_USER");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Alias = new Property(3, String.class, "alias", false, "ALIAS");
        public final static Property Weight = new Property(4, Double.class, "weight", false, "WEIGHT");
    }


    public PetSQLDao(DaoConfig config) {
        super(config);
    }
    
    public PetSQLDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PET_SQL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FK_ID_USER\" INTEGER," + // 1: fk_idUser
                "\"NAME\" TEXT," + // 2: name
                "\"ALIAS\" TEXT," + // 3: alias
                "\"WEIGHT\" REAL);"); // 4: weight
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PET_SQL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PetSQL entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer fk_idUser = entity.getFk_idUser();
        if (fk_idUser != null) {
            stmt.bindLong(2, fk_idUser);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(4, alias);
        }
 
        Double weight = entity.getWeight();
        if (weight != null) {
            stmt.bindDouble(5, weight);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PetSQL entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer fk_idUser = entity.getFk_idUser();
        if (fk_idUser != null) {
            stmt.bindLong(2, fk_idUser);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(4, alias);
        }
 
        Double weight = entity.getWeight();
        if (weight != null) {
            stmt.bindDouble(5, weight);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PetSQL readEntity(Cursor cursor, int offset) {
        PetSQL entity = new PetSQL( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // fk_idUser
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // alias
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4) // weight
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PetSQL entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFk_idUser(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAlias(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWeight(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PetSQL entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PetSQL entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PetSQL entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
