package pya.marlon.com.examplegreendao.sql.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TOY_SQL".
 */
@Entity
public class ToySQL {

    @Id(autoincrement = true)
    private Long id;
    private Integer fk_idPet;
    private String name;
    private Boolean isNew;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ToySQL() {
    }

    public ToySQL(Long id) {
        this.id = id;
    }

    @Generated
    public ToySQL(Long id, Integer fk_idPet, String name, Boolean isNew) {
        this.id = id;
        this.fk_idPet = fk_idPet;
        this.name = name;
        this.isNew = isNew;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFk_idPet() {
        return fk_idPet;
    }

    public void setFk_idPet(Integer fk_idPet) {
        this.fk_idPet = fk_idPet;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsNew() {
        return isNew;
    }

    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public String toString() {
        return "ToySQL{" +
                "id=" + id +
                ", fk_idPet=" + fk_idPet +
                ", name='" + name + '\'' +
                ", isNew=" + isNew +
                '}';
    }
}
